<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <link href="main3.css" rel="stylesheet">
        <title>African Short Stories</title>
    </head>
    <body>
        <section>
            <h2>The wisdom of the eagle and treachery of the Hyena</h2>
            <p>Hare was a very vain creature. He was always going around putting others down, and boasting about his won exploits.<br><br>One day tortoise got really fed up. “We’ll teach him a lesson”, he said. He sat by the roadside and waited for hare to come racing by. He called out to him: “Hare! Where are you going in such a hurry. Stop and listen to my proposal, which might be of some benefit to you.”<br><br>Hare turned round and approached tortoise. “What’s this I hear”, he said, “are you planning to give me some reward?”<br><br>“Indeed so”, said tortoise. “We are going to have a race! If you can beat me you will be able to call yourself the fastest in the animal kingdom”.<br><br>Hare fell over backwards laughing. “Beat you? That’s hardly a challenge. I could beat you in a race hopping on one leg!”<br><br>“We shall see”, said tortoise, “Do you accept the challenge?”<br><br>“Of course I do”, said hare, “It’ll be a gas!”<br><br>They determined the course of the race. Then tortoise went and called together some of his cousins, and gave them instructions to be at certain places along the race course. The next morning hare and tortoise met at the starting point. They set off together, but hare immediately rushed off, leaving tortoise far behind. After a few minutes he rested to get some breath. Then he set off again. To his great amazement he spotted tortoise in front of him. How was that possible? He’d only stopped for a minute! He raced past him, and shouted: “See if you can catch me again, shorty legs!” Within seconds he’d left tortoise far behind again.<br><br>Hare got tired again, and decided to have another little rest. There was no way he was going to lose this race! After a short while he set off again, at great speed, and lo! There was tortoise in front of him again! That was impossible! How could that slowcoach have overtaken him again? He caught up with tortoise and looked at him. “Have you taken some kind of magic potion?” he asked. Tortoise didn’t stop, he just said to hare: “Slow and steady, that’s me!”<br><br>Hare raced ahead. After a few minutes he looked back, there was no sign of tortoise and his self confidence returned. He stopped to have a nibble at a bush. He had a drink and a quick snooze to refresh himself, and then set off again, as fast as his strong legs could carry him. The finish of the race was now in sight. He looked up, and to his great consternation he saw that tortoise was just about to cross the line. He summoned all his strength, and made himself go as fast as the wind, but he crossed the line only to bump into tortoise, who was sitting there waiting for him! All the animals gathered were screaming and shouting.<br><br>Hare went off by himself, his ears drooping with sadness and shame. Tortoise and his cousins had a party to celebrate their victory.</p>
        </section>
    </body>
</html>
